import type { Metadata } from 'next';
import './globals.css';
import { Toaster } from 'react-hot-toast';
import Link from 'next/link';
import { Home, FileText, MessageSquare } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='h-full'>
      <body className='h-full flex bg-background text-foreground'>
        {/* Navigation Sidebar on the Left */}
        <nav className='fixed top-0 left-0 h-full w-64 bg-gray-800 text-white shadow-md overflow-y-auto'>
          <div className='p-4'>
            <Link
              href='/'
              className='text-xl font-semibold flex items-center space-x-2'
            >
              <Home className='h-6 w-6' />
              <span>My App</span>
            </Link>
          </div>
          <div className='mt-8 space-y-2'>
            <NavLink href='/' icon={<Home className='h-5 w-5' />} text='Home' />
            <NavLink
              href='/pdfs'
              icon={<FileText className='h-5 w-5' />}
              text='View PDFs'
            />
            <NavLink
              href='/library-chat'
              icon={<MessageSquare className='h-5 w-5' />}
              text='Library Chat'
            />
          </div>
        </nav>

        {/* Main Content Area */}
        <div className='flex-1 ml-64 flex flex-col'>
          <main className='flex-1 overflow-y-auto'>{children}</main>
        </div>

        <Toaster />
      </body>
    </html>
  );
}

function NavLink({
  href,
  icon,
  text,
}: {
  href: string;
  icon: React.ReactNode;
  text: string;
}) {
  return (
    <Link
      href={href}
      className='flex items-center space-x-2 px-4 py-2 hover:bg-gray-700 transition-colors'
    >
      {icon}
      <span>{text}</span>
    </Link>
  );
}
