import type { Metadata } from 'next';
import './globals.css';
import { Toaster } from 'react-hot-toast';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='h-full'>
      <body className='min-h-screen flex flex-col bg-gradient-to-br from-purple-50 to-purple-100'>
        <nav className='bg-purple-600 text-white shadow-md'>
          <div className='container mx-auto px-4 py-3 flex items-center justify-between'>
            <Link href='/' className='text-xl font-semibold'>
              My App
            </Link>
            <div className='space-x-4'>
              <Link
                href='/'
                className='hover:text-purple-200 transition-colors'
              >
                Home
              </Link>
              <Link
                href='/pdfs'
                className='hover:text-purple-200 transition-colors'
              >
                View PDFs
              </Link>
            </div>
          </div>
        </nav>
        <main className='flex-grow container mx-auto px-4 py-8'>
          {children}
        </main>
        <footer className='bg-purple-200 text-purple-600 py-4'>
          <div className='container mx-auto px-4 text-center'>
            © 2024 My App. All rights reserved.
          </div>
        </footer>
        <Toaster />
      </body>
    </html>
  );
}
